/** 
 * Accesed by `window._.delta` in the js console.
 * These properties are generated by [Nil](https://github.com/DxltaMath/Nil3).
*/
declare export default class delta {

    /** Always correct in timed problems */
    public static doNotRandomize : boolean;

    /** Allow escaping timed problems */
    public static allowEscapingTimed : boolean;

    /** temporary do not randomize */
    public static tempDnr : boolean | undefined;

}