/** 
 * Accesed by `window.delta` in the js console.
 * These properties are generated by [Nil](https://github.com/DxltaMath/public-Nil).
*/
declare export default class delta {

    /** Always correct in timed problems */
    public static doNotRandomize : boolean;

    /** Allow escaping timed problems */
    public static allowEscapingTimed : boolean;

}